spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: ["classpath*:/mapper/**/*.xml"]
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-fetch-size: 1000
  global-config:
    db-config:
      id-type: auto
