

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbac0WithDataScope
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      mode: always
#      platform: mysql
#      schema-locations: classpath:sql/mysql/schema-mysql.sql
#      data-locations: classpath:sql/mysql/data-mysql.sql

logging:
  level:
    # 打印sql
    com.example.rbac0withDatascope.dao.mapper: debug