

spring:
  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:sql/schema-mysql.sql
      data-locations: classpath:sql/data-mysql.sql

logging:
  level:
    # 打印sql
    com.example.rbac0withresource.dao.mapper: debug