

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/rbac0withresource
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

Auth:
  http:
    head:
      authHeadName: authorization
      loginName: username
      loginPass: password